@models = %w[
  EmploymentDetail
  MdmPolicy
  ActionPlanAlert
  ActionPlanReminder
  Agency
  MedicineAlertUser
  GroupcallAuthorisation
  MedicalCondition
  SchoolSubject
  HistoricalGroup
  AzureAdMapping
  Voice
  TimeBlock
  Pin
  MicrosoftTenant
  StigAuthorisation
  ApiCredential
  GoogleClassroomCredential
  OtpVerification
  PremisesAuditItem
  PremisesAudit
  UserStateLog
  InternalAudit
  DataAuditTechnical
  Audit
  Feature
  DeviceSession
  Characteristic
  DataAuditSecurity
  Subscription
  DeviceEvent
  DeviceAccess
  DataAuditPerson
  AutomaticLoginCredential
  TemporaryChild
  TemporaryUser
  TrainingCourse
  Agreement
  Treatment
  FirstAidOutcome
  KeywordExclusion
  SuggestedKeywordExclusionState
  ConcernKind
  Setting
  DataAuditLocation
  DataAuditItem
  Meeting
  ReferralComment
  Referral
  MainContact
  MeetingKind
  Medicine
  Capture
  Assignment
  NegativeCapture
  EmailAddress
  ConcernAlert
  ConcernReply
  TelephoneNumber
  Group
  Contact
  VettingRecord
  IdentificationCheck
  WebsiteList
  TeachingStatus
  CriminalRecordAssessment
  Membership
  Enrolment
  UserGroup
]
